-- Debugging queries for the EGA database

-- Select suitable analyses for the test run (further subsampling required!)
SELECT
  ANALYSIS_ID
FROM
  ANALYSIS
WHERE
  EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession') IS NOT NULL
  AND ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')

-- Fetch studies for the analyses of interest
SELECT DISTINCT
  EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/STUDY_REF/@accession')
FROM
  ANALYSIS
WHERE
  ANALYSIS_ID IN ('ERZ015305','ERZ015774','ERZ015903','ERZ016049','ERZ016157','ERZ016252','ERZ016381','ERZ016404','ERZ016497','ERZ017095')

-- ANALYSIS-REFSEQ table
SELECT
  ANALYSIS_ID, EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession')
FROM
  ANALYSIS
WHERE
  ANALYSIS_ID IN ('ERZ015305','ERZ015774','ERZ015903','ERZ016049','ERZ016157','ERZ016252','ERZ016381','ERZ016404','ERZ016497','ERZ017095')
ORDER BY
  ANALYSIS_ID

-- ANALYSIS-SAMPLE-TAXONOMY table
SELECT
  A_S.ANALYSIS_ID, A_S.SAMPLE_ID, EXTRACTVALUE(S.SAMPLE_XML, '/SAMPLE_SET/SAMPLE/SAMPLE_NAME/TAXON_ID')
FROM
  ANALYSIS_SAMPLE A_S
INNER JOIN
  SAMPLE S ON A_S.SAMPLE_ID = S.SAMPLE_ID
WHERE
  A_S.ANALYSIS_ID IN ('ERZ015305','ERZ015774','ERZ015903','ERZ016049','ERZ016157','ERZ016252','ERZ016381','ERZ016404','ERZ016497','ERZ017095')
ORDER BY
  ANALYSIS_ID, SAMPLE_ID



/* COUNT QUERIES */

-- Total counts of supported analyses types
SELECT ANALYSIS_TYPE, COUNT(ANALYSIS_TYPE)
FROM ANALYSIS
WHERE ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')
GROUP BY ANALYSIS_TYPE
ORDER BY ANALYSIS_TYPE

-- With accession
SELECT ANALYSIS_TYPE, COUNT(ANALYSIS_TYPE)
FROM ANALYSIS
WHERE EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession') IS NOT NULL
AND ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')
GROUP BY ANALYSIS_TYPE
ORDER BY ANALYSIS_TYPE

-- Without accession but with refname
SELECT ANALYSIS_TYPE, COUNT(ANALYSIS_TYPE)
FROM ANALYSIS
WHERE EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession') IS NULL
AND EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@refname') IS NOT NULL
AND ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')
GROUP BY ANALYSIS_TYPE
ORDER BY ANALYSIS_TYPE

-- Distinct refnames
SELECT refname, count(refname) AS rename_count
FROM (
  SELECT
    EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@refname') AS refname,
    EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession') AS accession
  FROM
    ANALYSIS
  WHERE 
    ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')
)
WHERE
  accession IS NULL
  AND refname IS NOT NULL
GROUP BY refname
ORDER BY rename_count DESC

-- Distinct custom assemblies
SELECT c_description, c_label, c_url, count(*) as c_count
FROM (
  SELECT
    EXTRACTVALUE(ANALYSIS_XML, '(/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/CUSTOM/DESCRIPTION)[1]') AS c_description,
    EXTRACTVALUE(ANALYSIS_XML, '(/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/CUSTOM/URL_LINK/LABEL)[1]') AS c_label,
    EXTRACTVALUE(ANALYSIS_XML, '(/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/CUSTOM/URL_LINK/URL)[1]') AS c_url
  FROM
    ANALYSIS
  WHERE 
    ANALYSIS_TYPE IN ('PROCESSED_READS', 'REFERENCE_ALIGNMENT', 'SEQUENCE_VARIATION')
    AND EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@refname') IS NULL
    AND EXTRACTVALUE(ANALYSIS_XML, '/ANALYSIS_SET/ANALYSIS/ANALYSIS_TYPE/*/ASSEMBLY/STANDARD/@accession') IS NULL
)
WHERE c_url IS NOT NULL
GROUP BY c_description, c_label, c_url
ORDER BY c_count DESC
